line-length = 120
target-version = "py311"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".data",
    ".mypy_cache",
]

[lint]
select = ["E", "F", "I", "N", "UP", "INP"]
ignore = []
per-file-ignores = {}
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
